language: node_js
node_js:
    - "5"
script:
    - npm run lint
before_install:
    - sh init.sh
    - mkdir private
    - openssl aes-256-cbc -K $encrypted_769a06cc899c_key -iv $encrypted_769a06cc899c_iv -in config.json.enc -out private/config.json -d
